### ISSUE TITLE
How to run MMGBSA with OpenMM?

### ISSUE THREAD

**Issue by mainguyenanhvu** [quantaosun/Ambertools-OpenMM-MD#1]
I found your code is used for running MMPBSA with openMM. 

Please help me to run MMGBSA. Thank you very much.

https://github.com/quantaosun/Ambertools-OpenMM-MD/blob/main/Ambertools-OpenMM-MD_GBSA.ipynb

**Comment by quantaosun** [comment]
Hi,
Sorry for the late reply. 
In the example above, we still use Amber's mmpbsa.py to run the job. 
OpenMM is able to run the Amber input by directly reading *prmtop and *inpcrd files.
```
from simtk.openmm import *
from simtk.openmm.app import *
from simtk.unit import *

# Input Files

prmtop = AmberPrmtopFile('complex.prmtop')
inpcrd = AmberInpcrdFile('complex.inpcrd')
```
So it is still exactly the same way as how Amber runs MMPBSA if you were familiar with Amber.
The two ```complex.prmtop``` and ```complex.inpcrd```is expected to be generated from scratch or with some third-party web servers like Charmm GUI. 

When using Charmm Gui, the output format may be a bit different, just replacing the two files with the equivalent one should be fine.

**Comment by mainguyenanhvu** [comment]
Thank you for your reply. 

I couldn't find two python scripts in your code: MMPBSA.py and ante-MMPBSA.py.

Please show me them. Thank you very much.

**Comment by quantaosun** [comment]
MMPBSA.py will be included automatically in the PATH if you have installed Ambertools.
For example, on Google Colab, you can do
1. Install conda
```
!pip install condacolab
import condacolab
condacolab.install_mambaforge()
```
2, Install Ambertools

```
!mamba install -c conda-forge ambertools -y
```
3, source the home directory of ambertools
```
amberhome = "source /usr/local/amber.sh"
```
4, check now MMPBSA.py should be working 

```
!MMPBSA.py -h
```
It would be very similar when doing this on any local Linux.

Quantao

**Comment by mainguyenanhvu** [comment]
Thank you very much. How about ante-MMPBSA.py?

**Comment by mainguyenanhvu** [comment]
Hi,

I run as your guide but it said: 
![image](https://github.com/quantaosun/Ambertools-OpenMM-MD/assets/26211591/ec458cc3-cedd-4648-8ecd-ff14bbc4b810)

I installed ambertools by using conda with version 23.3: 
![image](https://github.com/quantaosun/Ambertools-OpenMM-MD/assets/26211591/a8900ff3-615c-4b38-abd6-02b2ecbd12ab)

**Comment by pharm-dacnhan** [comment]
Hi, 
I am trying to prepare the ligand following your instruction to generate tleap. But I could not solve the bellow problem: 
<img width="512" alt="image" src="https://github.com/quantaosun/Ambertools-OpenMM-MD/assets/136064242/c164ccc8-e48b-4a07-9edf-e304e00abf90">

Could you please show me the way to figure out?

**Comment by pharm-dacnhan** [comment]
This is my ligand and protein files: 
https://drive.google.com/file/d/1_IH-GCgc8r3pN7qAgEBfKodbl9jCceGn/view?usp=share_link
https://drive.google.com/file/d/150q-7tIq5A-xCQZXcvxSToiEx7LpOlS9/view?usp=share_link

**Comment by quantaosun** [comment]
> Hi,
> 
> I run as your guide but it said: ![image](https://user-images.githubusercontent.com/26211591/261918510-ec458cc3-cedd-4648-8ecd-ff14bbc4b810.png)
> 
> I installed ambertools by using conda with version 23.3: ![image](https://user-images.githubusercontent.com/26211591/261918795-a8900ff3-615c-4b38-abd6-02b2ecbd12ab.png)

-----------------------------------
It was supposed to be an error since we haven't provided any input like mmpbsa.in file etc. It all looks good, just try to run a complete job with all proper input files MMPBSA.py needed. ante-MMPBSA.py should be already there as well.

**Comment by quantaosun** [comment]
Hi there,

You should change ```XEY``` to your ligand name, by checking your
ligand.pdb it seems your ligand name is ```*```, which is not quite usual.
This might due to you have used
different software with different manners to treat pdb files.

```

REMARK  99 MOE v2015.10 (Chemical Computing Group Inc.) Wed Aug 16 21:01:23
2023

HETATM    1  O     *     0     118.122 113.107 125.451  1.00  0.00
  O

HETATM    2  C     *     0     119.649 111.596 128.259  1.00  0.00
  C

HETATM    3  C     *     0     118.875 114.222 128.035  1.00  0.00
  C

HETATM    4  C     *     0     119.491 112.900 127.408  1.00  0.00
  C


```


I would suggest you modify your ligand.pdb file by any text editor, to
change * to any random three-litter name like UNK or ABC.


Then, modify the following cell


```

!awk '$4=="ABC"' your_complex.pdb > ligand1.pdb

```



pharm-dacnhan ***@***.***> 于2023年8月21日周一 14:54写道：

**Comment by mainguyenanhvu** [comment]
Hi @quantaosun,

When I run this cell: 
```
!ante-MMPBSA.py  -p complex.prmtop -c com.prmtop -r rec.prmtop -l ligand.prmtop -s :WAT:Na+:Cl-:Mg+:K+ -n :LIG --radii mbondi2
```

It said that:
```
Traceback (most recent call last):
  File "/usr/local/bin/ante-MMPBSA.py", line 82, in <module>
    parmed = which('parmed', search_path=True)
  File "/usr/local/lib/python3.10/site-packages/MMPBSA_mods/findprogs.py", line 71, in which
    amberhome = get_amberhome()
  File "/usr/local/lib/python3.10/site-packages/MMPBSA_mods/findprogs.py", line 62, in get_amberhome
    raise MMPBSA_Error('AMBERHOME is not set!') 
MMPBSA_mods.exceptions.MMPBSA_Error: AMBERHOME is not set!
```

And, when I run this cell: `!MMPBSA.py -O -i mmpbsa.in -o FINAL_RESULTS_MMPBSA_decomposition.dat -sp  complex.prmtop -cp com.prmtop -rp rec.prmtop -lp ligand.prmtop -y prot_lig_prod_all.dcd`, it throws:
```
Traceback (most recent call last):
  File "/usr/local/bin/MMPBSA.py", line 41, in <module>
    from MMPBSA_mods import main
  File "/usr/local/lib/python3.10/site-packages/MMPBSA_mods/main.py", line 43, in <module>
    from MMPBSA_mods.commandlineparser import parser
  File "/usr/local/lib/python3.10/site-packages/MMPBSA_mods/commandlineparser.py", line 60, in <module>
    default=os.path.join(os.getenv('AMBERHOME'), 'dat', 'mmpbsa',
  File "/usr/local/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Please help me to fix them. Thank you very much.

**Comment by quantaosun** [comment]
> Hi @quantaosun,
> 
> When I run this cell: 
> ```
> !ante-MMPBSA.py  -p complex.prmtop -c com.prmtop -r rec.prmtop -l ligand.prmtop -s :WAT:Na+:Cl-:Mg+:K+ -n :LIG --radii mbondi2
> ```
> 
> It said that:
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/ante-MMPBSA.py", line 82, in <module>
>     parmed = which('parmed', search_path=True)
>   File "/usr/local/lib/python3.10/site-packages/MMPBSA_mods/findprogs.py", line 71, in which
>     amberhome = get_amberhome()
>   File "/usr/local/lib/python3.10/site-packages/MMPBSA_mods/findprogs.py", line 62, in get_amberhome
>     raise MMPBSA_Error('AMBERHOME is not set!') 
> MMPBSA_mods.exceptions.MMPBSA_Error: AMBERHOME is not set!
> ```
> 
> And, when I run this cell: `!MMPBSA.py -O -i mmpbsa.in -o FINAL_RESULTS_MMPBSA_decomposition.dat -sp  complex.prmtop -cp com.prmtop -rp rec.prmtop -lp ligand.prmtop -y prot_lig_prod_all.dcd`, it throws:
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/MMPBSA.py", line 41, in <module>
>     from MMPBSA_mods import main
>   File "/usr/local/lib/python3.10/site-packages/MMPBSA_mods/main.py", line 43, in <module>
>     from MMPBSA_mods.commandlineparser import parser
>   File "/usr/local/lib/python3.10/site-packages/MMPBSA_mods/commandlineparser.py", line 60, in <module>
>     default=os.path.join(os.getenv('AMBERHOME'), 'dat', 'mmpbsa',
>   File "/usr/local/lib/python3.10/posixpath.py", line 76, in join
>     a = os.fspath(a)
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> ```
> 
> Please help me to fix them. Thank you very much.

Hi,

Have you run the following command before try mmpbsa ?

amberhome = "source /usr/local/amber.sh"
.

It looks like just due to you haven't set AMBERHOME variable.

**Comment by mainguyenanhvu** [comment]
Hi @quantaosun, I run it, but there is still an error announced. 

![image](https://github.com/quantaosun/Ambertools-OpenMM-MD/assets/26211591/b5ebd1a5-37e9-49f8-9b1f-d6e7286a16d5)

![image](https://github.com/quantaosun/Ambertools-OpenMM-MD/assets/26211591/b7f80484-7d06-4d51-b420-a8365a851ef3)

**Comment by mainguyenanhvu** [comment]
I tried this command, it  worked:
```
import os
os.environ['AMBERHOME'] = "/usr/local"
!echo $AMBERHOME
!source "$AMBERHOME/amber.sh"
```
